### ISSUE TITLE
Response 403

### ISSUE THREAD

**Issue by zeromentu** [mariolatiffathy/GetByetHostCookie#3]
Hello, im trying to use your bypass method, and using your example it gives me 403 error
Am i doing anything wrong? Is there any free method for doing this?

Thanks in advanced

**Comment by oddmario** [comment]
Hello,

This project hasn't received any updates for more than a year and iFastNet probably changed the way it works.
Unfortunately I don't have much time to contribute to this project right now.
You are always welcome to open a PR.

Kind regards.
